version: "2"
checks:
  argument-count:
    config:
      threshold: 7
  complex-logic:
    config:
      threshold: 15
  file-lines:
    config:
      threshold: 350
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 75
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    enabled: true